feature:
  rocketmq:
    enabled: ${ROCKETMQ_ENABLED:true}

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: ${spring.application.name}-producer
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    retry-next-server: true
    access-key: ${ROCKETMQ_ACCESS_KEY:}
    secret-key: ${ROCKETMQ_SECRET_KEY:}
  consumer:
    group: ${spring.application.name}-consumer
    consume-thread-min: 5
    consume-thread-max: 32
    consume-message-batch-max-size: 1
    pull-batch-size: 32
    access-key: ${ROCKETMQ_ACCESS_KEY:}
    secret-key: ${ROCKETMQ_SECRET_KEY:}
    await-termination-millis: 10000
    suspend-current-queue-time-millis: 100
    delay-level: 1

---
spring:
  config:
    activate:
      on-profile: docker
rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:rocketmq-namesrv:9876}
